### PR TITLE
Adding origin and mid servers to cdn-in-a-box

### PR DESCRIPTION
**Pull request by ocket8888**
JSON files and setup scripts need to be reviewed to ensure I'm doing everything the right way, but requests complete successfully and TP UI shows origin server with a fully-set-up cdn/division/region/deliveryservice and mid with associated profile and params.

### CODE REVIEW

**Comment by dangogh** [comment]
I attempted to rebase to master,  but ended up with a ton of conflicts -- mostly within files introduced by this PR.   Please do a `git rebase -i` and squash those repeated commits and push that up again..

**Comment by dangogh** [comment]
also,   best not to submit a PR with `master` as your base branch.  That makes it harder to do any unrelated work.

**Comment by ocket8888** [comment]
Okay, I think maybe I got it this time

**Comment by ocket8888** [comment]
Alright, I'll just start over

**Pull request closed without merging**
