### PR TITLE
Added mid and origin servers, DS configuration

### PR DESCRIPTION
**Pull request by ocket8888**

### CODE REVIEW

**Comment by dangogh** [comment]
a couple of files missing Apache license headers...   can you fix that?

**Comment by dangogh** [comment]
not needed in .json files -- they can't have comments,  but just about anything else can and must

**Comment by ocket8888** [comment]
got it

**Comment by ocket8888** [comment]
done

**Comment by ocket8888** [comment]
submitting PR to apache/trafficcontrol instead

**Pull request closed without merging**
